[tool.poetry]
name = "lp-parser"
version = "1.0.0"
description = ""
authors = ["zombyacoff, lazerofmagma"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tuparser = "^0.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
