[package]
name = "rust_module"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_module"
crate-type = ["cdylib"]

[dependencies]
fancy-regex = "0.13.0"
pyo3 = { version = "0.21.2", features = ["extension-module"] }

[profile.release]
debug = true      
lto = true         
codegen-units = 1 
