offset:
  offset: false
  value: 2 # minimum 2

release_date:
  release_date: false
  years:
  - 2024

websites_list: # example: https://telegra.ph/steam
- ""

exceptions_list: # telegra.ph: dmca@telegram.org
- ""

# DON'T TOUCH IF YOU DON'T WHAT ARE YOU DOING
for_advanced_users:
  login_regex: \S+@\S+\.\S+ # All logins are a email
  password_regex: \S*\d\S* # All words that contain a digit are considered a password
